apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendapi3-deployment
  namespace: api
spec:
  selector:
    matchLabels:
      app: frontend3
  template:
    metadata:
      labels:
        app: frontend3
    spec:
      containers:
      - name: frontendapi3-container
        image: app11_api:latest
        imagePullPolicy: Never
        env:
          - name: DBServer
            value: mssql-service
          - name: DBPort
            value: "1433"
          - name: DBUser
            value: sa
          - name: DBPassword
            value: "Qwerty@12345"
          - name: Database
            value: webapidemodb
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
        ports:
        - containerPort: 80

