apiVersion: v1
kind: Service
metadata:
  name: frontendapi3-service
  namespace: api
  labels:
    run: frontendapi3-service
spec:
  selector:
    app: frontend3
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: NodePort

