apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-deployment
  namespace: api
spec:
  selector:
    matchLabels:
      app: frontend3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontend3
    spec:
      terminationGracePeriodSeconds: 10
      hostname: sqlserver
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql-container
        image: app11_sqlserver:latest
        imagePullPolicy: Never
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: "Qwerty@12345"
        - name: MSSQL_PID
          value: "Developer"
        ports:
        - containerPort: 1433
          name: mssql-port
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-claim


